Дипломный проект. Этап 2. Версия 1
Armmacham/java-explore-with-me pull request #4
Opened 2023-07-26 10:36 UTC by Armmacham

2023-07-30 14:37 UTC, NikolaiDem requested changes

2023-07-30 14:37 UTC, NikolaiDem commented on ewm-service/src/main/java/ru/practicum/ewmservice/compilation/service/CompilationServiceImpl.java
> +                                        eventService.getEventShortListWithSort(compilation.getEvents(), false)))
Здесь проблема N+1 запроса из-за viewsMap и confirmedRequestMap

2023-07-30 14:37 UTC, NikolaiDem commented on ewm-service/src/main/java/ru/practicum/ewmservice/event/dao/EventEntity.java
> +    @OneToOne(fetch = FetchType.EAGER, cascade = CascadeType.MERGE)
Одна категория только у одного события может быть?
Аналогично для initiator

2023-07-30 14:37 UTC, NikolaiDem commented on ewm-service/src/main/java/ru/practicum/ewmservice/location/dao/LocationEntity.java
> +public class LocationEntity {
Почему Location сделан вынесен в отдельную таблицу?
И у Event Location задан как 1 к 1. А если у всех событий одна и та же локация, то должны ли быть созданы одинаковые Location для каждого события?

2023-07-30 14:37 UTC, NikolaiDem commented on ewm-service/src/main/java/ru/practicum/ewmservice/request/dao/RequestEntity.java
> +    @OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
Один юзер только один запрос может создать?
Аналогично для event

2023-07-30 14:37 UTC, NikolaiDem commented on ewm-service/src/main/java/ru/practicum/ewmservice/request/service/RequestServiceImpl.java
> +            requestRepository.save(request);
Лучше вызвать saveAll(...)

2023-07-30 14:37 UTC, NikolaiDem commented on ewm-service/src/main/java/ru/practicum/ewmservice/request/service/RequestServiceImpl.java
> +                    return requestRepository.save(r);
Лучше вызвать saveAll(...)

2023-07-30 14:37 UTC, NikolaiDem commented on ewm-service/src/main/java/ru/practicum/ewmservice/request/service/RequestServiceImpl.java
> +                    return requestRepository.save(r);
Лучше вызвать saveAll(...)

2023-07-30 14:37 UTC, NikolaiDem commented on ewm-service/src/main/java/ru/practicum/ewmservice/statistics/StatConfig.java
> +    public ServiceStatsClient createClient() {
Почему сделан кастомный бин?

2023-07-30 18:30 UTC, Armmacham commented on ewm-service/src/main/java/ru/practicum/ewmservice/admin/controller/AdminController.java
> +            @Min(0) @RequestParam(value = "from", defaultValue = "0", required = false) int from,
Удалил необязательное определение для аргументов с значением по умолчанию

2023-08-01 16:01 UTC, NikolaiDem commented on ewm-service/src/main/java/ru/practicum/ewmservice/category/repository/CategoryRepository.java
> +@Repository
Не исправлено для остальных репозиториев

2023-08-01 16:03 UTC, NikolaiDem commented on ewm-service/src/main/java/ru/practicum/ewmservice/admin/controller/AdminController.java
> +            @Min(0) @RequestParam(value = "from", defaultValue = "0", required = false) int from,
Validated нужен там, где есть аннотации из javax.constraints

2023-08-01 16:04 UTC, NikolaiDem approved these changes

2023-08-03 10:54 UTC, merged